site_name: GOKB - Global Open Knowledge Base
copyright: Copyright &copy; GOKB 2014 -
use_directory_urls: false
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
  favicon: assets/favicon-16x16.png
  logo: assets/gokb_logo_white_250px.png
  custom_dir: theme/
  font: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc
  - admonition
plugins:
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - build: true
          default: true
          locale: en
          name: EN
        - build: true
          default: false
          locale: de
          name: DE
          nav_translations:
            Contact: Kontakt
            Create and edit packages: Anlegen und Pflege von Paketen
            Create and edit provider: Anlegen und Pflege von Anbietern
            Documentation: Dokumentation
            Get involved: Beteiligen Sie sich
            Guidelines for package names: Richtlinien für Paketnamen
            Imprint: Impressum
            KBART editing: Bearbeitung von KBART-Dateien
            KBART introduction: Einführung in KBART
            KBART validator: KBART-Validator
            Presentations: Präsentationen
            Privacy Policy: Datenschutzerklärung
            Publications: Publikationen
            Registration and login: Registrierung und Anmeldung
            Working with review requests: Arbeiten mit Prüfanfragen
      reconfigure_material: true
      reconfigure_search: true
  - search
  - offline
nav:
  - Home: index.md
  - News: news.md
  - Documentation:
    - KBART introduction: documentation/kbart-introduction.md
    - Registration and login: documentation/registration-and-login.md
    - Create and edit provider: documentation/create-and-edit-provider.md
    - Create and edit packages: documentation/create-and-edit-packages.md
    - Working with review requests: documentation/review-requests.md
    - Guidelines for package names: documentation/guidelines-for-package-names.md
    - KBART validator: documentation/kbart-validator.md
    - KBART editing: documentation/kbart-editing.md
  - Presentations: presentations.md
  - Publications: publications.md
  - Releases: releases.md
  - Get involved: get-involved.md
  - Contact:
    - Contact: contact/contact.md
    - Imprint: contact/imprint.md
    - Privacy Policy: contact/privacypolicy.md
not_in_nav: |
    /accessibility.de.md
    /accessibility.en.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GOKb1
    - icon: fontawesome/brands/github
      link: https://github.com/openlibraryenvironment/gokb
