site_name: GOKb - Global Open Knowledgebase
copyright: Copyright &copy; GOKb 2014 -
use_directory_urls: false
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.top
  favicon: assets/favicon-16x16.png
  logo: assets/favicon-32x32.png
  custom_dir: theme
  font: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
plugins:
  - i18n:
      default_language: en
      languages:
        en: EN
        de: DE
      nav_translations:
        de:
          Contact: Kontakt
          Get involved: Beteiligen Sie sich
          Documentation: Dokumentation
          Imprint: Impressum
          Presentations: Präsentationen
          Privacy Policy: Datenschutzerklärung
          Publications: Publikationen
          KBART introduction: Einführung in KBART
          Registration and login: Registrierung und Anmeldung
          Create and edit provider: Anlegen und Pflege von Anbietern
          Create and edit packages: Anlegen und Pflege von Paketen
          Working with review requests: Arbeiten mit Prüfanfragen
          Guidelines for package names: Richtlinien für Paketnamen
          KBART validator: KBART-Validator
          KBART editing: Bearbeitung von KBART-Dateien
  - search
  - localsearch
nav:
  - Home: index.md
  - News: news.md
  - Documentation:
    - KBART introduction: documentation/kbart-introduction.md
    - Registration and login: documentation/registration-and-login.md
    - Create and edit provider: documentation/create-and-edit-provider.md
    - Create and edit packages: documentation/create-and-edit-packages.md
    - Working with review requests: documentation/review-requests.md
    - Guidelines for package names: documentation/guidelines-for-package-names.md
    - KBART validator: documentation/kbart-validator.md
    - KBART editing: documentation/kbart-editing.md
  - Presentations: presentations.md
  - Publications: publications.md
  - Releases: releases.md
  - Get involved: get-involved.md
  - Contact:
    - Contact: contact/contact.md
    - Imprint: contact/imprint.md
    - Privacy Policy: contact/privacypolicy.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GOKb1
    - icon: fontawesome/brands/github
      link: https://github.com/openlibraryenvironment/gokb
