name: ci 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs[i18n]==1.3.0
      - run: pip install mkdocs-static-i18n==0.45
      - run: pip install mkdocs-material==8.2.14
      - run: pip install mkdocs-localsearch==0.9.1
      - run: mkdocs gh-deploy --force
