name: ci 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs==1.2.2
      - run: pip install mkdocs[i18n]
      - run: pip install mkdocs-static-i18n==0.19
      - run: pip install mkdocs-material==7.3.1
      - run: pip install mkdocs-localsearch==0.9.1
      - run: mkdocs gh-deploy --force
